version: 0.2
phases:
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - aws ecr get-login-password --region ap-northeast-3 | docker login --username AWS --password-stdin 124355663661.dkr.ecr.ap-northeast-3.amazonaws.com
  build:
    commands:
      - echo Building Docker image...
      # Dockerfile is in the root directory, so we can build directly from the root context.
      - docker build -t newg2-repo -f Dockerfile .
      # Tag the built image with the ECR repository URI
      - docker tag newg2-repo:latest 124355663661.dkr.ecr.ap-northeast-3.amazonaws.com/newg2-repo:frontend
  post_build:
    commands:
      - echo Pushing Docker image to ECR...
      - docker push 124355663661.dkr.ecr.ap-northeast-3.amazonaws.com/newg2-repo:frontend
      - echo Writing image definitions...
      - printf '[{"name":"FrontEnd","imageUri":"124355663661.dkr.ecr.ap-northeast-3.amazonaws.com/newg2-repo:frontend"}]' > imagedefinitions.json
artifacts:
  files: imagedefinitions.json
